In [7]:
#one dimensional 
import numpy as np
arr=np.array([1,2,3,4]) 
print(arr)
type(arr)

[1 2 3 4]


numpy.ndarray

In [9]:
#two dimensional 
import numpy as np
arr=np.array([[1,2,3,4],[1,2,3,4]])
print(arr)


[[1 2 3 4]
 [1 2 3 4]]


numpy.ndarray

In [13]:

import numpy as np
arr=np.array(20)
print(arr)


20


In [1]:
import numpy as np
x=np.array([1,2,3,4])
r=x.reshape(2,2)
print(r)

[[1 2]
 [3 4]]


In [2]:
import numpy as np
array = np.ones((6,5))
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
import numpy as np 
array = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(array)




[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
import numpy as np 
array = np.identity(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
import numpy as np 
array = np.full((2,3),3)
print(array)

[[3 3 3]
 [3 3 3]]


In [7]:
import numpy as np 
array = np.identity(7)
print(array[2:5,0:3])

[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
import numpy as np 
array = np.identity(7)
print(array)
print(array[-3:-1,3:-1])


[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]]
