In [1]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
b=np.array([[2,2,0],[1,0,1],[0,1,0]])
print(a)
print(b)

[[1 0 2]
 [2 1 1]
 [3 0 3]]
[[2 2 0]
 [1 0 1]
 [0 1 0]]


In [3]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
b=np.array([[2,2,0],[1,0,1],[0,1,0]])
print(a)
print(b)
a.flags

[[1 0 2]
 [2 1 1]
 [3 0 3]]
[[2 2 0]
 [1 0 1]
 [0 1 0]]


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [2]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
b=np.array([[2,2,0],[1,0,1],])
b.shape
a.shape

(3, 3)

In [4]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.strides

(12, 4)

In [5]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.ndim

2

In [6]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.data

In [7]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.size

9

In [8]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.itemsize

4

In [9]:
import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.base

In [ ]:

import numpy as np
a=np.array([[1,0,2],[2,1,1],[3,0,3]])
a.nbytes